apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-service-config
  namespace: jaehyeong-tech-dev
data:
  PORT: "3006"
  NODE_ENV: development
  OCI_REGION: ap-seoul-1
  MAX_FILE_SIZE: "10485760"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/gif,image/webp,application/pdf,video/mp4"
