apiVersion: v1
kind: Secret
metadata:
  name: storage-service-secret
  namespace: jaehyeong-tech-dev
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-storage:5432/storage_db
  RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
  OCI_NAMESPACE: your-oci-namespace
  OCI_BUCKET: jaehyeong-tech
  OCI_ACCESS_KEY: your-oci-access-key
  OCI_SECRET_KEY: your-oci-secret-key
