apiVersion: v1
kind: Secret
metadata:
  name: comment-service-secret
  namespace: jaehyeong-tech-dev
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-comment:5432/comment_db
  RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
