apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaehyeong-tech-dev

resources:
  - peer-authentication.yaml
  - authorization-policy.yaml
  - destination-rule.yaml
  - request-authentication.yaml
  - virtual-service.yaml
