apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: jaehyeong-tech-dev
data:
  # PostgreSQL 데이터베이스 이름들
  AUTH_DB_NAME: auth_db
  BLOG_DB_NAME: blog_db
  COMMENT_DB_NAME: comment_db
  STORAGE_DB_NAME: storage_db
  ANALYTICS_DB_NAME: analytics_db
  PAGE_DB_NAME: page_db
